name: build-apk

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: build release apk
        run: ./gradlew assembleRelease --stacktrace

      - name: Sign Release APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        continue-on-error: true

      - name: Force Sign with Debug Key if Unsigned
        run: |
          if [ -f "app/build/outputs/apk/release/app-release-unsigned.apk" ]; then
            echo "Ozel imza bulunamadi, standart anahtarla imzalanıyor..."
            # Android SDK icindeki varsayilan debug anahtariyla APK'yi hizlica imzalayip cikartiyoruz
            apksigner sign --ks $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --ks ~/.android/debug.keystore --ks-pass pass:android --key-pass pass:android --out app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/app-release-unsigned.apk
          fi

      - name: Rename Signed APK to app-release.apk
        run: |
          if [ -f "app/build/outputs/apk/release/app-release-signed.apk" ]; then
            mv app/build/outputs/apk/release/app-release-signed.apk app/build/outputs/apk/release/app-release.apk
          fi

      - name: Generate Release Tag
        id: release_tag
        run: |
          echo "tag=v$(date +'%Y.%m.%d-%H%M')-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          tag_name: ${{ steps.release_tag.outputs.tag }}
          name: "Build ${{ steps.release_tag.outputs.tag }}"
          draft: false
          prerelease: false
          files: app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
